### ISSUE TITLE
Generic: Undefined Index: end_line error

### ISSUE THREAD

**Issue by tmgast** [Gert-dev/php-integrator-annotations#4]
I'm getting this error nearly every time I edit a file. With this package disabled, the message never comes up. So I believe this may be the issue origin.

```
php-integrator - Oops, something went wrong!
PHP sent back something unexpected. This is most likely an issue with your setup. If you're sure this is a bug, feel free to report it on the bug tracker.
 
→ 
Notice: Undefined index: end_line in /Users/tgast/.atom/packages/php-integrator-base/php/src/IndexDataAdapter.php on line 366
```

**Comment by Gert-dev** [comment]
Thanks for taking the time to debug this, as I mentioned in the ticket on the base package, you were right in reporting it there originally. I'll follow this up there [1].

[1] https://github.com/Gert-dev/php-integrator-base/issues/106
